crudapp/urls.py
from django.urls import path
from crudapp.views import *



urlpatterns = [
    path('',index,name='index'),
    #path('emp', emp,name='emp'),  
    path('show/',show,name='show'),  
    path('edit/<int:id>',edit,name='edit'),  
    path('update/<int:id>',update,name='update'),  
    path('delete/<int:id>',delete,name='delete'),
    #path('deactivate/<int:user_id>/', views.deactivate_user, name='deactivate_user'),
    path('project/',project,name='project'),
    path('department/',department,name='department'),
    path('departmentlab/',departmentlab,name='departmentlab'),
    path('order/',order,name='order'),
    path('customer/',customer,name='customer'),
    path('showcustomerorder/',showcustomerorder,name='showcustomerorder'),
    
    #path('customerorder<str:name>/',customerorder, name='customerorder' ),
    

]

crudproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('crudapp.urls'))

]


#setting the URL for MEDIA
urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

crudapp/models.py
from django.db import models

# Create your models here.


class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length = 15)
    img = models.ImageField(upload_to='uploads/')
    
    #class meta:
      ##  db_table = 'employee'
class Project(models.Model):
  #unique_identifier = models.CharField(max_length=50, primary_key=True)
  CATEGORY_CHOICES = [
    ("tech", "Technology"),
    ("food", "Food"),
    ("travel", "Travel")

  ]

  projecttitle = models.CharField(max_length=100)
  category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, null =True)
  approveddate =models.DateTimeField(auto_now_add=False, blank=True)
  startdate = models.DateTimeField(auto_now_add=True,blank=True)
  enddate = models.DateTimeField(auto_now_add=False,blank=True)
  projectcost=(models.FloatField)


  employee= models.OneToOneField(Employee, on_delete=models.CASCADE, null=True)


class Department(models.Model):
  CATEGORY_CHOICES = [
    ('tech', 'Technology'),
    ('food', 'Food'),
    ('travel', 'Travel'),  
    
  ]

  departmenttitle = models.CharField(max_length=100)
  category = models.CharField(max_length=10, choices=CATEGORY_CHOICES, null =True)
  approveddate =models.DateTimeField(auto_now_add=False, blank=True)
  startdate = models.DateTimeField(auto_now_add=True,blank=True)
  enddate = models.DateTimeField(auto_now_add=False,blank=True)
  Totalearnings=(models.FloatField)
  

  employee =models.OneToOneField(Employee,on_delete=models.CASCADE, null=True)

  #implementing many-to-one.

class Customer(models.Model):
  name = models.CharField(max_length=100)
  email = models.EmailField()

  def __str__(self):
    return self.name

   
   ##implementing a Customer to many orders.

class Order(models.Model):

  CATEGORY_PRODUCT = [
    ('TV', 'LG Plasma'),
    ('MV', 'Micro Wave'),
    ('FR', 'Freezer'),  
    
  ]

  customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
  product = models.CharField(max_length=50, choices=CATEGORY_PRODUCT, null =True)  
  order_date = models.DateTimeField(auto_now_add=True)
  total_amount = models.DecimalField(max_digits=10, decimal_places=2)

  def __str__(self):
    return f"Order #{self.id} by {self.customer}"

crudapp/forms.py
from django import forms
from crudapp.models import *


class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = "__all__"

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = "__all__"  
        widgets ={
            'approveddate': forms.SelectDateWidget(),
            'enddate':forms.SelectDateWidget(),
        } 
           
class DepartmentForm(forms.ModelForm):

    class Meta:
        model = Department
        fields = "__all__"  
        widgets ={
            'approveddate': forms.SelectDateWidget(),
            'enddate':forms.SelectDateWidget(),
       }  

class CustomerForm(forms.ModelForm):

    class Meta:
        model =Customer
        fields = "__all__" 

class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = "__all__" 
        

crudapp/views.py
from django.shortcuts import render,redirect
from crudapp.forms import  *
from crudapp.models import Employee  
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404
from django.contrib import messages


# Create your views here.
def index(request):
    if request.method == "POST":
        form = EmployeeForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Employee data saved successfully!")
                return render(request, 'crudapp/index.html', {'form':form})
            except Exception as e:
                messages.error(request, f"An error occured: {str(e)}") 

    else:
        form = EmployeeForm()  
    return render(request, 'crudapp/index.html', {'form': form})                 
    




def show(request):  
    employees = Employee.objects.all().order_by("-id")  
    return render(request,'crudapp/show.html',{'employees':employees})  

def edit(request, id):  
    employee = Employee.objects.get(id=id)  
    return render(request,'crudapp/edit.html', {'employee':employee})  

def update(request, id):  
    employee = Employee.objects.get(id=id)  
    form = EmployeeForm(request.POST, instance = employee)  
    if form.is_valid():  
        form.save()  
        return redirect("/show/")  
    return render(request, 'crudapp/edit.html', {'employee': employee})  

def delete(request, id):  
    employee = Employee.objects.get(id=id)  
    employee.delete()  
    return redirect("/show/")  

def deactivate_user(request, user_id):
    user = get_object_or_404(User, id=user_id)

    if user.is_active:
        user.is_active = False
        user.save()
        # You might want to add a success message here
    else:
        # User is already deactivated
        pass

    # Redirect or render a template


def project(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Project saved successfully!")
                return render(request, 'crudapp/project.html', {'form':form})
            except Exception as e:
                messages.error(request, f"An error occured: {str(e)}") 

    else:
        form = ProjectForm()  
    return render(request, 'crudapp/project.html', {'form': form}) 



def department(request):
    if request.method == "POST":
        form = DepartmentForm(request.POST)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "saved successfully!")
                return render(request, 'crudapp/department.html', {'form':form})
            except Exception as e:
                messages.error(request, f"An error occured: {str(e)}") 

    else:
        form = DepartmentForm()  
    return render(request, 'crudapp/department.html', {'form': form}) 


def departmentlab(request):  
    departments = Department.objects.all().order_by("-id")  
    return render(request,'crudapp/departmentlab.html',{'departments':departments})  




def order(request):
    if request.method == "POST":
        form = OrderForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Customer order saved successfully!")
                return render(request, 'crudapp/order.html', {'form':form})
            except Exception as e:
                messages.error(request, f"An error occured: {str(e)}") 

    else:
        form = OrderForm()  
    return render(request, 'crudapp/order.html', {'form': form})  



def customer(request):
    if request.method == "POST":
        form = CustomerForm(request.POST,request.FILES)
        if form.is_valid():
            try:
                form.save()
                messages.success(request, "Customer details saved successfully!")
                return render(request, 'crudapp/customer.html', {'form':form})
            except Exception as e:
                messages.error(request, f"An error occured: {str(e)}") 

    else:
        form = CustomerForm()  
    return render(request, 'crudapp/customer.html', {'form': form})  

def showcustomerorder (request):  
    customer = Order.objects.all().order_by("-id")  
    return render(request,'crudapp/showcustomerorder.html',{'customer':customer})  
  

crudapp/templates/crudapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title%} {% endblock title %}</title>
    <script src="{% static 'crudapp/js/script.js'%}"></script>
    <link rel="stylesheet" href="{% static 'crud/css/style.css' %}"/>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css">
    <!-- Optitonal theme -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css">
    <!-- Latest compiled and minifies Javascript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrapp@3.3.7/dist/js/bootstrap.min.js"></script>
</head>
<body>
    {% include 'crudapp/header.html' %}
    {% block rightbar %}

    {% endblock rightbar %}
    
    {% block content %}

    {% endblock content %}

    {% block leftbar %}

    {% endblock leftbar %}
    {% include 'crudapp/footer.html' %}
</body>
</html>

crudapp/templates/crudapp/customer.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form"  enctype="multipart/form-data">  
    {% csrf_token %}  
<div class="container">  
<br>
{% if messages %}  
<div class="messages">
 {% for message in messages %}
  <div class=" alert alert-{{messages.tags}}">
   {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% if form.errors %}
<div class="alert alert-danger">
 <p>errors occured:</p>
 <ul>
   {% for field_name, error_messages in form.errors.items %}
    <li>{{ field_name}}: {{error_messages|join:","}} </li>
  {% endfor %}
 </ul>
</div>
{% endif %}
<br>
<div class="form-group row"> 
<span><a href='/showcustomerorder/' class='btn btn-primary'> All Order </a></span> 

<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4"> 
<h3>Enter Details</h3>  
</div>  
</div>   
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Name:</label>  
<div class="col-sm-4">  
  {{ form.name }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Email:</label>  
<div class="col-sm-4">  
  {{ form.email }}  
</div>  
</div>  

<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock content %}

crudapp/templates/crudapp/department.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form"  enctype="multipart/form-data">  
    {% csrf_token %}  
<div class="container">  
<br>
{% if messages %}  
<div class="messages">
 {% for message in messages %}
  <div class=" alert alert-{{messages.tags}}">
   {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% if form.errors %}
<div class="alert alert-danger">
 <p>errors occured:</p>
 <ul>
   {% for field_name, error_messages in form.errors.items %}
    <li>{{ field_name}}: {{error_messages|join:","}} </li>
  {% endfor %}
 </ul>
</div>
{% endif %}
<br>
<div class="form-group row"> 
<span><a href='/departmentlab/' class='btn btn-primary'> All Department </a></span> 

<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4"> 
<h3>Enter Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Department Title:</label>  
<div class="col-sm-4">  
  {{ form.departmenttitle }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Category:</label>  
<div class="col-sm-4">  
  {{ form.category }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Approved date:</label>  
<div class="col-sm-4">  
  {{ form.approveddate }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Start date:</label>  
<div class="col-sm-4">  
  {{ form.startdate }}  
</div>  
</div>
<div class="form-group row">  
<label class="col-sm-2 col-form-label">End date:</label>  
<div class="col-sm-4">  
  {{ form.enddate }}  
</div>  
</div> 
 <div class="form-group row">  
<label class="col-sm-2 col-form-label">Totalearnings:</label>  
<div class="col-sm-4">  
  {{ form.totalearnings }}  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee :</label>  
<div class="col-sm-4">  
  {{ form.employee }}  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock content %}

crudapp/templates/crudapp/departmentlab.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Department Title</th>  
        <th>Category</th>  
        <th>Approved date</th>  
        <th>Start date</th>  
        <th>End date</th> 
         <th>Employee</th>
    </tr>  
    </thead>  
    <tbody>  
{% for department in departments %}  
    <tr>  
        <td>{{ department.departmenttitle }}</td>  
        <td>{{ department.category }}</td>  
        <td>{{ department.approveddate }}</td>  
        <td>{{ department.startdate }}</td> 
         <td>{{ department.enddate }}</td>
         <td>{{ department.employee }}</td>
        <td>  
            
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  


{% endblock %}

crudapp/templates/crudapp/edit.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form" action="/update/{{employee.id}}">  
    {% csrf_token %}  
<div class="container">  
<br>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<h3>Update Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Id:</label>  
<div class="col-sm-4">  
    <input type="text" name="eid" id="id_eid" required maxlength="20" value="{{ employee.eid }}"/>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Name:</label>  
<div class="col-sm-4">  
    <input type="text" name="ename" id="id_ename" required maxlength="100" value="{{ employee.ename }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Email:</label>  
<div class="col-sm-4">  
    <input type="email" name="eemail" id="id_eemail" required maxlength="254" value="{{ employee.eemail }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Contact:</label>  
<div class="col-sm-4">  
    <input type="text" name="econtact" id="id_econtact" required maxlength="15" value="{{ employee.econtact }}" />  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-success">Update</button> 
<a href="/delete/{{employee.id}}" class="btn btn-danger">Delete</a>
</div>  
</div>  
</div>  
</form>   

{% endblock %}

crudapp/templates/crudapp/index.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form"  enctype="multipart/form-data">  
    {% csrf_token %}  
<div class="container">  
<br>
{% if messages %}  
<div class="messages">
 {% for message in messages %}
  <div class=" alert alert-{{messages.tags}}">
   {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% if form.errors %}
<div class="alert alert-danger">
 <p>errors occured:</p>
 <ul>
   {% for field_name, error_messages in form.errors.items %}
    <li>{{ field_name}}: {{error_messages|join:","}} </li>
  {% endfor %}
 </ul>
</div>
{% endif %}
<br>
<div class="form-group row"> 
<span><a href='/show/' class='btn btn-primary'> All Employees </a></span> 

<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4"> 
<h3>Enter Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Id:</label>  
<div class="col-sm-4">  
  {{ form.eid }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Name:</label>  
<div class="col-sm-4">  
  {{ form.ename }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Email:</label>  
<div class="col-sm-4">  
  {{ form.eemail }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Contact:</label>  
<div class="col-sm-4">  
  {{ form.econtact }}  
</div>  
</div>
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee Image:</label>  
<div class="col-sm-4">  
  {{ form.img }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock content %}

crudapp/templates/crudapp/order.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form"  enctype="multipart/form-data">  
    {% csrf_token %}  
<div class="container">  
<br>
{% if messages %}  
<div class="messages">
 {% for message in messages %}
  <div class=" alert alert-{{messages.tags}}">
   {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% if form.errors %}
<div class="alert alert-danger">
 <p>errors occured:</p>
 <ul>
   {% for field_name, error_messages in form.errors.items %}
    <li>{{ field_name}}: {{error_messages|join:","}} </li>
  {% endfor %}
 </ul>
</div>
{% endif %}
<br>
<div class="form-group row"> 
<span><a href='/showcustomerorder/' class='btn btn-primary'> All Order </a></span> 

<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4"> 
<h3>Enter Details</h3>  
</div>  
</div>  

<div class="form-group row">  
<label class="col-sm-2 col-form-label">Customer:</label>  
<div class="col-sm-4">  
  {{ form.customer }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Product:</label>  
<div class="col-sm-4">  
  {{ form.product }}  
</div>  
</div>
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Order date:</label>  
<div class="col-sm-4">  
  {{ form.order_date }}  
</div>  
</div> 
 <div class="form-group row">  
<label class="col-sm-2 col-form-label">Total Amount:</label>  
<div class="col-sm-4">  
  {{ form.total_amount }}  
</div>  
</div> 

<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock content %}

crudapp/templates/crudapp/project.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<form method="POST" class="post-form"  enctype="multipart/form-data">  
    {% csrf_token %}  
<div class="container">  
<br>
{% if messages %}  
<div class="messages">
 {% for message in messages %}
  <div class=" alert alert-{{messages.tags}}">
   {{ message }}
  </div>
  {% endfor %}
</div>
{% endif %}
{% if form.errors %}
<div class="alert alert-danger">
 <p>errors occured:</p>
 <ul>
   {% for field_name, error_messages in form.errors.items %}
    <li>{{ field_name}}: {{error_messages|join:","}} </li>
  {% endfor %}
 </ul>
</div>
{% endif %}
<br>
<div class="form-group row"> 
<span><a href='/show/' class='btn btn-primary'> All Employees </a></span> 

<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4"> 
<h3>Enter Details</h3>  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Project Title:</label>  
<div class="col-sm-4">  
  {{ form.projecttitle }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Category:</label>  
<div class="col-sm-4">  
  {{ form.category }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Approved date:</label>  
<div class="col-sm-4">  
  {{ form.approveddate }}  
</div>  
</div>  
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Start date:</label>  
<div class="col-sm-4">  
  {{ form.startdate }}  
</div>  
</div>
<div class="form-group row">  
<label class="col-sm-2 col-form-label">End date:</label>  
<div class="col-sm-4">  
  {{ form.enddate }}  
</div>  
</div> 
 <div class="form-group row">  
<label class="col-sm-2 col-form-label">Project cost:</label>  
<div class="col-sm-4">  
  {{ form.projectcost }}  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-2 col-form-label">Employee :</label>  
<div class="col-sm-4">  
  {{ form.employee }}  
</div>  
</div> 
<div class="form-group row">  
<label class="col-sm-1 col-form-label"></label>  
<div class="col-sm-4">  
<button type="submit" class="btn btn-primary">Submit</button>  
</div>  
</div>  
</div>  
</form>  

{% endblock content %}

crudapp/templates/crudapp/show.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Employee ID</th>  
        <th>Employee Name</th>  
        <th>Employee Email</th>  
        <th>Employee Contact</th>  
        <th>Actions</th>  
    </tr>  
    </thead>  
    <tbody>  
{% for employee in employees %}  
    <tr>  
        <td>{{ employee.eid }}</td>  
        <td>{{ employee.ename }}</td>  
        <td>{{ employee.eemail }}</td>  
        <td>{{ employee.econtact }}</td>  
        <td>  
            <a href="/edit/{{ employee.id }}"><span class="glyphicon glyphicon-pencil" >Edit</span></a>  
            <a href="/delete/{{ employee.id }}">Delete</a>  
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  
<br>  
<br>  
<center><a href="/" class="btn btn-primary">Add New Record</a></center>

{% endblock %}

crudapp/templates/crudapp/showcustomerorder.html
{% extends 'crudapp/base.html' %}
{% load static%}
{% block title %} {{ section.title }} {% endblock %}

{% block content %}

<table class="table table-striped table-bordered table-sm">  
    <thead class="thead-dark">  
    <tr>  
        <th>Customer Name</th>
        

        
    </tr>  
    </thead>  
    <tbody>  
{% for list in customer %}  
    <tr>  
        <td>{{ order.customer }}</td>   
        
        <td>  
            <a href="/customerorder/{{ customer.customer }}"><span class="glyphicon glyphicon-pencil" >Show All Orders</span></a>  
            
        </td>  
    </tr>  
{% endfor %}  
    </tbody>  
</table>  


{% endblock %}